import React, { useState } from 'react';
import { MominAILogo, AppIcons } from './icons.tsx';

interface DashboardProps {
    onLogout: () => void;
}

const Dashboard: React.FC<DashboardProps> = ({ onLogout }) => {
    const [activeView, setActiveView] = useState('projects');

    const handleOpenIDE = () => {
        window.location.href = '/?ide=true';
    };

    const renderView = () => {
        switch(activeView) {
            case 'projects':
                return <ProjectsView onOpenIDE={handleOpenIDE} />;
            case 'account':
                return <AccountView />;
            default:
                return <ProjectsView onOpenIDE={handleOpenIDE} />;
        }
    };
    
    return (
        <div className="flex h-screen w-screen bg-[var(--background)] text-[var(--foreground)]">
            <Sidebar activeView={activeView} setActiveView={setActiveView} />
            <div className="flex-1 flex flex-col overflow-hidden">
                <Header onLogout={onLogout} />
                <main className="flex-1 overflow-y-auto p-8 bg-gradient-to-br from-[var(--background)] to-[var(--background-secondary)]">
                   {renderView()}
                </main>
            </div>
        </div>
    );
};

const Sidebar: React.FC<{activeView: string, setActiveView: (view: string) => void}> = ({ activeView, setActiveView }) => {
    const navItems = [
        { id: 'projects', label: 'Projects', icon: AppIcons.Briefcase },
        { id: 'account', label: 'Account', icon: AppIcons.User },
        { id: 'settings', label: 'Settings', icon: AppIcons.Settings },
    ];

    return (
        <aside className="w-64 bg-[rgba(18,15,36,0.5)] border-r border-[var(--border-color)] flex flex-col p-4">
            <div className="px-2 mb-10">
                <MominAILogo />
            </div>
            <nav className="flex-1 flex flex-col gap-2">
                {navItems.map(item => (
                    <button 
                        key={item.id}
                        onClick={() => setActiveView(item.id)}
                        className={`flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors duration-200 ${activeView === item.id ? 'bg-[var(--accent)] text-white' : 'text-[var(--gray)] hover:bg-[var(--background-secondary)] hover:text-[var(--foreground)]'}`}
                    >
                        <item.icon className="w-5 h-5" />
                        <span>{item.label}</span>
                    </button>
                ))}
            </nav>
        </aside>
    );
};

const Header: React.FC<{onLogout: () => void}> = ({ onLogout }) => (
    <header className="flex-shrink-0 h-16 flex items-center justify-between px-8 border-b border-[var(--border-color)]">
        <h1 className="text-xl font-semibold">Welcome Back</h1>
        <div className="flex items-center gap-4">
             <button onClick={onLogout} className="flex items-center gap-2 text-sm text-[var(--gray)] hover:text-[var(--foreground)] transition-colors">
                <AppIcons.LogOut className="w-5 h-5" />
                <span>Logout</span>
            </button>
        </div>
    </header>
);

const ProjectsView: React.FC<{onOpenIDE: () => void}> = ({ onOpenIDE }) => (
    <div>
        <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold">Your Projects</h2>
            <button className="flex items-center gap-2 bg-[var(--accent)] text-white px-4 py-2 rounded-lg font-semibold text-sm hover:brightness-110 transition-all">
                <AppIcons.Plus className="w-5 h-5" />
                <span>New Project</span>
            </button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* Project Card */}
            <div className="bg-[var(--background-secondary)] p-6 rounded-xl border border-[var(--border-color)] flex flex-col gap-4 group hover:border-[var(--accent)] transition-all duration-300">
                <h3 className="text-lg font-semibold">My Web App</h3>
                <p className="text-sm text-[var(--gray)] flex-1">A production-ready web application generated by MominAI.</p>
                <div className="flex justify-between items-center">
                    <span className="text-xs text-[var(--gray)]">Updated 2 hours ago</span>
                    <button onClick={onOpenIDE} className="bg-white/10 text-white px-4 py-2 rounded-lg text-sm font-semibold hover:bg-[var(--accent)] transition-colors">
                        Open IDE
                    </button>
                </div>
            </div>
             {/* New Project Placeholder */}
            <div className="border-2 border-dashed border-[var(--border-color)] rounded-xl flex items-center justify-center text-center p-6 hover:border-[var(--accent)] hover:text-[var(--accent)] transition-colors duration-300 cursor-pointer">
                <div>
                    <AppIcons.Plus className="w-8 h-8 mx-auto mb-2" />
                    <span className="font-semibold">Create New Project</span>
                </div>
            </div>
        </div>
    </div>
);

const AccountView = () => (
     <div>
        <h2 className="text-2xl font-bold mb-6">Account Settings</h2>
        <div className="max-w-md bg-[var(--background-secondary)] p-8 rounded-xl border border-[var(--border-color)]">
            <form className="flex flex-col gap-4">
                 <div>
                    <label className="text-sm text-[var(--gray)] mb-1 block">Name</label>
                    <input type="text" value="Demo User" className="w-full p-2 bg-[var(--background)] rounded-md border border-[var(--border-color)] outline-none focus:ring-2 focus:ring-[var(--accent)]" />
                </div>
                 <div>
                    <label className="text-sm text-[var(--gray)] mb-1 block">Email</label>
                    <input type="email" value="user@example.com" disabled className="w-full p-2 bg-[var(--background)] rounded-md border border-[var(--border-color)] opacity-60" />
                </div>
                <button type="submit" className="mt-4 bg-[var(--accent)] text-white px-4 py-2 rounded-lg font-semibold text-sm hover:brightness-110 transition-all">
                    Save Changes
                </button>
            </form>
        </div>
    </div>
);


export default Dashboard;
